# Generated by Django 5.0 on 2023-12-21 01:04

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_post', 'Can add post'), ('change_post', 'Can change post'), ('view_post', 'Can view post')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_groups',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_user_permissions',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.permission'),
        ),
    ]
